---
   - name: Check the NameSpace
     command: kubectl get ns "{{ ns }}"
     register: names
     ignore_errors: true
   - name: print the output
     debug: var=names
     ignore_errors: true
   - name: Creating Name Space
     community.kubernetes.k8s:
      name: "{{ ns }}"
      api_version: v1
      kind: Namespace
      state: present
     when: names.stdout == ""
