---
- name: Name
  hosts: all
  vars_prompt:
   - name: ns
     prompt: "Enter the name space"
     private: no
   - name: pod_name
     prompt: "Enter the Pod Name"
     private: no
  collections:
   - community.kubernetes.k8s
  roles:
   - namespace
   - pod
  environment:
   KUBECONFIG: /home/ansible/.kube/config
